---
title: "RNASeq"
output:
  html_document:
    theme: lumen        
    highlight: tango     
    toc: true            
    toc_float: true
    code_folding: hide 
    number_sections: true     
    df_print: paged      
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  results = 'hide',  
  message = FALSE,   
  warning = FALSE)
```

Environmental Setup

```{r library imports}
library(tidyverse)
library(DESeq2)
library(EnsDb.Hsapiens.v86)
library(EnhancedVolcano)
library(dplyr)
library(ggplot2)
library(pheatmap)
```

Data import and EDA

```{r upload and inspect metadata}
rse <- readRDS("EwS.rds")
cd <- as.data.frame(colData(rse))
View(cd)
```

```{r}
colData(rse) <- colData(rse)[, c("sample", "run", "condition")]    # select data for analysis
rse$condition <- factor(rse$condition)                             # change raw text to factor format
rse$condition <- relevel(rse$condition, ref = "shCTR")             # assign the control factor explicitly
```

```{r}
all(rownames(colData(rse)) == colnames(assay(rse)))                # check if the metadata match count matrix
```
```{r}
assay(rse)[1:5, 1:5]    # check the genes designation
```

```{r}
# make the gene names readable for annotation
rownames(rse) <- gsub(pattern = "\\..+", replacement = "", x = rownames(rse))    
assay(rse)[1:5, 1:5]
```

```{r}
all(assay(rse) == floor(assay(rse)))    # possible to inspect element or check via function
```













