---
title: "Single-Cell RNA-Seq"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(Seurat)
library(tidyverse)
library(ggpubr)
library(Matrix)
library(ggplot2)
library(patchwork)
library(SingleR)
library(celldex)
library(SingleCellExperiment)
```

```{r}
if (!file.exists("melanoma_matrix.tar.gz")) {
  download.file(
    url = "https://cf.10xgenomics.com/samples/cell-exp/8.0.0/10k_Human_DTC_Melanoma_3p_nextgem_10k_Human_DTC_Melanoma_3p_nextgem/10k_Human_DTC_Melanoma_3p_nextgem_10k_Human_DTC_Melanoma_3p_nextgem_count_sample_filtered_feature_bc_matrix.tar.gz",
    destfile = "melanoma_matrix.tar.gz",
    method = "curl"
  )
}
```


```{r}
if (!dir.exists("sample_filtered_feature_bc_matrix")) {
  untar("melanoma_matrix.tar.gz")
}
list.dirs(recursive = FALSE)
```

```{r}
mat <- Read10X(data.dir = "sample_filtered_feature_bc_matrix")
melanoma_raw <- CreateSeuratObject(counts = mat, project = "Melanoma_10k")
```

```{r}
View(mat)
View(melanoma_raw)
```

```{r}
melanoma_raw <- melanoma_raw |> 
  PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt")

VlnPlot(melanoma_raw, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
FeatureScatter(melanoma_raw, feature1 = "nCount_RNA", feature2 = "percent.mt")
```

```{r}
melanoma <- melanoma_raw |> 
  subset(subset = nFeature_RNA > 500 & nFeature_RNA < 6000 & percent.mt < 10) |>  
  NormalizeData() |> 
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000) |> 
  ScaleData()

# check the results
melanoma |> 
  FeatureScatter(feature1 = "nCount_RNA", feature2 = "percent.mt") +
  theme_bw()
```
#### PCA
```{r}
melanoma <- RunPCA(melanoma)

DimPlot(melanoma)

# What are the genes that determine PC1 and PC2?
VizDimLoadings(melanoma, dims = 1:2)
```


```{r}
FeaturePlot(melanoma, features = c("S100A1", "CST3", "EDNRB"))

FeaturePlot(melanoma, features = c("LYZ", "TYROBP"))

# Select number of PCs
ElbowPlot(melanoma, ndims = 50)
```

```{r}
melanoma <- melanoma |> 
  FindNeighbors(dims = 1:25) |> 
  FindClusters(resolution = 0.5) |>  
  RunUMAP(dims = 1:25)

DimPlot(melanoma, reduction = "umap", label = TRUE) + NoLegend()
```



